#!/bin/bash

# Vibrant Corporate Dashboard Assets Download Script
# Generated by Antigravity

# Directory
DEST_DIR="src/components/admin/dashboard"
mkdir -p "$DEST_DIR"

# Screenshot
echo "Downloading screenshot..."
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujQm48riiR2pAw3zixU9wB1-WGNyBPnHOhamL6qfKylJlR7yuZFcFK9VDvYDDadNvifL7i2HRXmWBMvar2eTmDvOumxp4Ps9nKnyURr0MSdrgvBlrsxry86YeTjtfrdnb5iOELt49q4vr9-EYuh1HllLtqJT4VusC-5mYjTup92W_yotM2jzmLdHOLYDsbRO_hAw7K5R63Z8hmkcRlx4plkjUBXt3GARnH1onRwYVJU4QK2miP8HJ5WpQU" -o "$DEST_DIR/vibrant-dashboard.png"

# HTML Code
echo "Downloading HTML code..."
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzIyMGYzNGY4MWZkMTRiYjk4NjAyNGU1MTRkMGQ5NDk0EgsSBxCPgvec8RcYAZIBIwoKcHJvamVjdF9pZBIVQhM3NjY3MTY2NzI4MjA0NTgwNjU0&filename=&opi=89354086" -o "$DEST_DIR/vibrant-dashboard.html"

echo "Done."
